package com.company.common;

/**
 * Created by weng on 2019/11/28.
 */
public enum CommunicateStatus {
    LOG_OUT,
    NO_PERMISSION,
    LOG_IN_NEEDED,
    CONNECTION_BUILD,
    REGISTER_SUCCEED,
    REGISTER_FAILED,
    LOGIN_FAILED,
    LOGIN_SUCCEED,
    FILE_TRANSFER_SUCCEED,
    BUILD_NOTIFICATION_CHANNEL,
    NO_SUCH_FILE,
    DELETE_FAILED,
    DELETE_SUCCESSFULLY

}
